services:
  frontend:
    build: ./Playlisten-frontend
    image: tall15421542/playlisten-deploy:frontend_prod_v1
    ports:
      - 3000:3000
    command: npm run dev
  backend:
    build: ./PlayListen-backend
    image: tall15421542/playlisten-deploy:backend_prod_v1
    ports:
      - 8000:8000
  webserver:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
